### ISSUE TITLE
The viewer used in paper's illustrations

### ISSUE THREAD

**Issue by TneitaP** [ranahanocka/point2mesh#12]
Both the illustrations in the paper and the animations in this repo was so appealing!  Could you provide some information about rendering methods and using 3D renderer？ Thank you!

**Comment by ranahanocka** [comment]
Hi @TneitaP ,

Blender was used for all the 3D rendering & animations. For the 2D illustrations, adobe illustrator was used.
For development purposes, I have started using [polyscope](https://github.com/nmwsharp/polyscope), which is fast and has some nice capabilities like coloring edges. 

-Rana

**Comment by TneitaP** [comment]
Thanks for your guidance and recommendations!
