### ISSUE TITLE
GPU out of memory，have some way to reduce the requirement

### ISSUE THREAD

**Issue by ZJH2233** [ranahanocka/point2mesh#13]
Thank for your job,
I GPU memory just 6g.
At 1000 or 2000 iter，ManiFold upsampled the faces,would report 'RuntimeError:CUDA out of memory'
in the past,I will adjust the batchsize when have this problems,but in your code seems to be no it.In the paper used 1080Ti and 2080Ti have 11g GPUmemory and in 6 part DISCUSSION said ' our method is quite expensive in terms of time and memory'.
So,There is no way to run this code used 6g memory？I don't care the runtime.

**Comment by ranahanocka** [comment]
If you are running out of memory, you can increase the # of parts here https://github.com/ranahanocka/point2mesh/blob/c56d89b993efc625c6e8c74040f974bdfe0d5127/options.py#L70

and the resolution per part is defined here:
https://github.com/ranahanocka/point2mesh/blob/c56d89b993efc625c6e8c74040f974bdfe0d5127/options.py#L28

where right now under 8000 faces is 1 part, under 16000 is 2 parts, and so on.

So for example, I think `lookup_num_parts = [1, 4, 8, 16] `might work. If not, you can also lower the 8000 threshold.

**Comment by HeCraneChen** [comment]
Hi Rana, I also ran in to the memory problem and I tried to use two GPUs in parallel in order to solve this problem but ran into some trouble. I tried to use nn.Dataparallel in line 425 of networks.py to put "net" into parallel GPUs. But that doesn't work and will report an error. Any advice?

**Comment by ZJH2233** [comment]
Thanks very much.I run programs on the CPU and get final result.If I have to use GPU, I will try the method you provide.
Thank you again for your outstanding work.

**Comment by ranahanocka** [comment]
Hi @HeCraneChen --

It should be possible to put the network on two GPUs in parallel  -- but you should also split up the mesh into the # of GPUs as well. For example, if you had 2 GPUs you can split the mesh in two parts, and run it in parallel.
