### ISSUE TITLE
Slides availability

### ISSUE THREAD

**Issue by DandiC** [ranahanocka/point2mesh#14]
Hi,

Congratulations on this work! Much like MeshCNN, this is a great idea/implementation in a beautifully written paper. I was wondering if the slides of this project will eventually be available. There is a link to them on the project's page, but it does not work.

Thanks!

**Comment by ranahanocka** [comment]
Hi @DandiC --

Thank you! I added the slide deck now to the website. Enjoy :)

-Rana

**Comment by DandiC** [comment]
Thank you!
